spring:
  application:
    name: product-service
  
  # Database Configuration (MySQL)
  datasource:
    url: jdbc:mysql://localhost:3306/product_service?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root                # <-- replace with your MySQL username
    password: Kithmir@786         # <-- replace with your MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update           # create/update tables automatically
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  # Flyway (optional, can be enabled later)
  flyway:
    enabled: false

# Server Configuration
server:
  port: 8082

# Eureka Client (if using service discovery)
# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka
#   instance:
#     prefer-ip-address: true
