# Port for this notification-service
server:
  port: 8085

# Spring Application Name
spring:
  application:
    name: notification-service

  # KAFKA CONFIGURATION
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.notification.kafka.model"

  # # --- GMAIL (SMTP) CONFIGURATION - CURRENTLY ACTIVE ---
  # mail:
  #   host: smtp.gmail.com
  #   port: 587 # Port for TLS/STARTTLS
  #   username: ${GMAIL_USERNAME} # <-- Your full Gmail address (e.g., your-email@gmail.com)
  #   password: ${GMAIL_APP_PASSWORD} # <-- The 16-character App Password you just generated
  #   properties:
  #     mail:
  #       smtp:
  #         auth: true
  #         starttls:
  #           enable: true # This is required for Gmail

  mail:
    host: localhost
    port: 1025
    username: ''
    password: ''
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
        

  # --- MAILTRAP CONFIGURATION - COMMENTED OUT FOR LATER USE ---
  # mail:
  #   host: smtp.mailtrap.io
  #   port: 2525
  #   username: ${MAILTRAP_USERNAME}
  #   password: ${MAILTRAP_PASSWORD}
  #   properties:
  #     mail:
  #       smtp:
  #         auth: true
  #         starttls:
  #           enable: true