version: "3.8"
services:
  mongodb:
    image: mongo:6.0
    container_name: mongo_customer
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: customer_db
    volumes:
      - mongo_data:/data/db

  mysql:
    image: mysql:8.0
    container_name: mysql_product
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: product_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mongo_data:
  mysql_data:

