# version: "3.8"
# services:
#   mongodb:
#     image: mongo:6.0
#     container_name: mongo_customer
#     ports:
#       - "27017:27017"
#     environment:
#       MONGO_INITDB_DATABASE: customer_db
#     volumes:
#       - mongo_data:/data/db

#   mysql:
#     image: mysql:8.0
#     container_name: mysql_product
#     ports:
#       - "3306:3306"
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_DATABASE: product_db
#     volumes:
#       - mysql_data:/var/lib/mysql

# volumes:
#   mongo_data:
#   mysql_data:



version: "3.8"

services:
  # --- DATABASE for Customer Service ---
  mongodb:
    image: mongo:6.0
    container_name: mongo_customer
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: customer_db
    volumes:
      - mongo_data:/data/db

  # --- DATABASE for Product & Order Services ---
  mysql:
    image: mysql:8.0
    container_name: mysql_product
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: product_db
    volumes:
      - mysql_data:/var/lib/mysql

  # --- KAFKA INFRASTRUCTURE ---
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      # Exposes Kafka to your local machine (e.g., for your Spring Boot apps)
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      # This listener is for communication FROM your local machine TO Kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  mongo_data:
  mysql_data:
