spring:
  # MongoDB Configuration
  data:
    mongodb:
      host: localhost
      port: 27017
      database: customer_db

# Server Configuration
server:
  port: 8081

# Eureka Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true